### PR TITLE
First change

### PR DESCRIPTION
**Pull request by scarroy**
another

### CODE REVIEW

**Comment by scarroy** [comment]
still trying

**Review by scarroy — COMMENTED** [review]
looks good

**Comment by DickChesterwood** [comment]
Hi, I think you need to be doing this against your own organization - the course shows how to fork this organization into your own. Hope it goes ok!

**Comment by scarroy** [comment]
Hi,

I caught that after the fact. Thank you. Your Kubernetes class was well done and informative. I'll continue investigating Helm and look forward to your listio class.

Regards,
Steve Arroyo
August 7, 2020 4:16 AM, "Richard Chesterwood"  wrote:
	Hi, I think you need to be doing this against your own organization - the course shows how to fork this organization into your own. Hope it goes ok!

**Pull request closed without merging**
